### ISSUE TITLE
Empty orders

### ISSUE THREAD

**Issue by ching-wang** [hughgrigg/poprobincards#414]
https://github.com/hughgrigg/poprobincards/blob/master/app/Modules/Sales/Http/Controllers/Customer/StripeController.php#L73

Undefined variable: order (/var/www/poprobincards/app/Modules/Sales/Http/Controllers/Customer/StripeController.php:73)

**Comment by hughgrigg** [comment]
https://github.com/hughgrigg/poprobincards/pull/446
