### ISSUE TITLE
Add 'specific offers' on home page

### ISSUE THREAD

**Issue by ching-wang** [hughgrigg/poprobincards#642]
The current offer badge can not be seen for mobile phone users. Can we add 'specific offers' on the home page for mobile phone users? 

![default](https://user-images.githubusercontent.com/5269283/46909907-566b7f00-cf32-11e8-95d2-1a0160c921cd.png)

vs

![default](https://user-images.githubusercontent.com/5269283/46909913-68e5b880-cf32-11e8-9324-af847015bbeb.png)

**Comment by hughgrigg** [comment]
https://github.com/hughgrigg/poprobincards/pull/647
